package basic.bit.application;

/**
 * source: https://leetcode.com/problems/find-the-difference/
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then
 * add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 *   Input:
 *     s = "abcd"
       t = "abcde"

     Output:
       e

   Explanation:
     'e' is the letter that was added.
 * Created by zhou-jg on 2017/1/12.
 */
public class DifferenceFinder {

    public static char find(String s, String t){
        int i =0;
        int sum = 0;
        for (; i<s.length(); i++){
            sum = sum ^ s.charAt(i) ^ t.charAt(i);
        }
        sum ^= t.charAt(i);
        return (char) sum;
    }
}
